server:
  port: 8080
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/polldb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        jdbc.lob.non_contextual_creation: true
        show_sql: true
        generate_statistics: true
  flyway:
    baselineOnMigrate: true
---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/polldb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none