server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/polldb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  flyway:
    baselineOnMigrate: true
---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/polldb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none